### ISSUE TITLE
Team Selection Rule Breaks Plugin

### ISSUE THREAD

**Issue by Grimlock7** [Flashback083/TrainerItem#1]
Adding an item requirement to an NPCTrainer with Team Selection rule enabled breaks it if you try battling them without having the required Item, You are stuck on the Team selection screen unable to proceed or back out resulting in having to close your client
<img width="748" alt="2018-08-27_19-59-56" src="https://user-images.githubusercontent.com/30302995/44680267-22490700-aa35-11e8-9038-fb16046d5563.png">

**Comment by Flashback083** [comment]
Fix in v2.6.2
