### ISSUE TITLE
Ne prend pas en compte les stacks

### ISSUE THREAD

**Issue by Areolame** [Flashback083/TrainerItem#3]
En résumé : J'ai ajouté un required item et je le possédais en stack
Il a refusé le combat car il ne voyait pas l'item, mais quand j'en mets un de côté il le voit.
Je suppose donc que c'est un problème de stack

**Comment by Flashback083** [comment]
Ah c'est un bug connu mais je peux pas le fix je pense, mais je garde un oeil dessus merci
