### ISSUE TITLE
On ne peut pas "sortir" du /tiinfo

### ISSUE THREAD

**Issue by Areolame** [Flashback083/TrainerItem#4]
J'ai donc fait entièrement mon PNJ, mais j'ai voulu ensuite éditer son skin. Sauf que dès que je faisais un clique droit avec le pixelmon:trainer_editor il continuait à me donner des informations sur le PNJ. 
J'ai pu retirer cela en faisant un clique droit sur le PNJ à côté. Un détails en soit mais un peu dérangeant si on ne connaît pas.

**Comment by Flashback083** [comment]
Plop, essaye /ticancel et dis moi si la commande existe

**Comment by Flashback083** [comment]
Ya le /ticancel pour enlever ce soucis, par contre, ça sera sur le serv au prochain redem
